swagger: "2.0"
info:
  description: "This is the api documentation for loggerhead - biotascape's location recommendation api. To learn more about it checkout [loggerhead](https://github.com/erebuseternal/loggerhead)."
  version: "1.0.0"
  title: "loggerhead"
  contact:
    email: "marcelsanders96@gmail.com"
host: "localhost"
basePath: "/loggerhead/v0"
tags:
- name: "regions"
  description: "Recommended regions"
  externalDocs:
    description: "Find out more"
    url: "https://github.com/erebuseternal/loggerhead"
schemes:
- "https"
- "http"
paths:
  /regions:
    get:
      tags:
      - "regions"
      summary: "Get recommended regions"
      description: ""
      operationId: "regions"
      produces:
      - "application/json"
      parameters:
      - name: "taxa"
        in: "query"
        description: "High level taxa to filter results on"
        required: true
        type: "array"
        items:
          type: "string"
          enum:
          - "Plantae"
          - "Animalia"
          - "Mollusca"
          - "Reptilia"
          - "Aves"
          - "Amphibia"
          - "Actinopterygii"
          - "Mammalia"
          - "Insecta"
          - "Arachnida"
          - "Fungi"
          - "Protozoa"
          - "Chromista"
          default: "Animalia"
        collectionFormat: "multi"
      - name: "nelat"
        in: "query"
        description: "Latitude of northeast corner of bounding box for search"
        type: "number"
        required: true
      - name: "nelng"
        in: "query"
        description: "Longitude of northeast corner of bounding box for search"
        type: "number"
        required: true
      - name: "swlat"
        in: "query"
        description: "Latitude of southwest corner of bounding box for search"
        type: "number"
        required: true
      - name: "swlng"
        in: "query"
        description: "Longitude of southwest corner of bounding box for search"
        type: "number"
        required: true
      responses:
        "200":
          description: "successful operation"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/Region"
        "400":
          description: "Invalid input"
definitions:
  Coords:
    type: "object"
    required:
    - "lat"
    - "lng"
    properties:
      lat: 
        type: "number"
      lng: 
        type: "number"
  Row:
    type: "object"
    properties:
      image:
        type: "string"
        format: "uri"
      cols:
        type: "array"
        items:
          type: "string"
  Section:
    type: "object"
    properties:
      title:
        type: "string"
      headers:
        type: "array"
        items: 
          type: "string"
      rows:
        type: "array"
        items:
          $ref: "#/definitions/Row"
  Info:
    type: "object"
    properties:
      title:
        type: "string"
      sections:
        type: "array"
        items:
          $ref: "#/definitions/Section"
  Region:
    type: "object"
    required:
    - "name"
    - "photoUrls"
    properties:
      id:
        type: "integer"
        format: "int64"
      polygon:
        type: "array"
        items:
          $ref: "#/definitions/Coords"
      info:
        $ref: "#/definitions/Info"
      subregions:
        type: "array"
        items:
          type: "integer"
externalDocs:
  description: "Find out more about Swagger"
  url: "http://swagger.io"